[2023-05-13T10:44:17.228+0530] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: test2.consume_from_kafka_task manual__2023-05-12T08:06:19.570573+00:00 [queued]>
[2023-05-13T10:44:17.236+0530] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: test2.consume_from_kafka_task manual__2023-05-12T08:06:19.570573+00:00 [queued]>
[2023-05-13T10:44:17.236+0530] {taskinstance.py:1331} INFO - Starting attempt 1 of 2
[2023-05-13T10:44:17.254+0530] {taskinstance.py:1350} INFO - Executing <Task(PythonOperator): consume_from_kafka_task> on 2023-05-12 08:06:19.570573+00:00
[2023-05-13T10:44:17.258+0530] {standard_task_runner.py:57} INFO - Started process 10413 to run task
[2023-05-13T10:44:17.263+0530] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'test2', 'consume_from_kafka_task', 'manual__2023-05-12T08:06:19.570573+00:00', '--job-id', '173', '--raw', '--subdir', 'DAGS_FOLDER/test.py', '--cfg-path', '/tmp/tmp_e2b1v_k']
[2023-05-13T10:44:17.264+0530] {standard_task_runner.py:85} INFO - Job 173: Subtask consume_from_kafka_task
[2023-05-13T10:44:17.310+0530] {task_command.py:410} INFO - Running <TaskInstance: test2.consume_from_kafka_task manual__2023-05-12T08:06:19.570573+00:00 [running]> on host nizam-HP-15-Notebook-PC
[2023-05-13T10:44:17.379+0530] {taskinstance.py:1568} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='test2' AIRFLOW_CTX_TASK_ID='consume_from_kafka_task' AIRFLOW_CTX_EXECUTION_DATE='2023-05-12T08:06:19.570573+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-05-12T08:06:19.570573+00:00'
[2023-05-13T10:44:17.383+0530] {conn.py:380} INFO - <BrokerConnection node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: connecting to localhost:9092 [('127.0.0.1', 9092) IPv4]
[2023-05-13T10:44:17.384+0530] {conn.py:1205} INFO - Probing node bootstrap-0 broker version
[2023-05-13T10:44:17.384+0530] {conn.py:418} ERROR - Connect attempt to <BrokerConnection node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]> returned error 111. Disconnecting.
[2023-05-13T10:44:17.384+0530] {conn.py:919} INFO - <BrokerConnection node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2023-05-13T10:44:17.433+0530] {conn.py:380} INFO - <BrokerConnection node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: connecting to localhost:9092 [('127.0.0.1', 9092) IPv4]
[2023-05-13T10:44:17.434+0530] {conn.py:418} ERROR - Connect attempt to <BrokerConnection node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]> returned error 111. Disconnecting.
[2023-05-13T10:44:17.434+0530] {conn.py:919} INFO - <BrokerConnection node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2023-05-13T10:44:17.434+0530] {taskinstance.py:1847} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/nizam/env_airflow/lib/python3.10/site-packages/airflow/operators/python.py", line 181, in execute
    return_value = self.execute_callable()
  File "/home/nizam/env_airflow/lib/python3.10/site-packages/airflow/operators/python.py", line 198, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/home/nizam/airflow/dags/test.py", line 23, in consume_from_kafka
    consumer = KafkaConsumer(
  File "/home/nizam/env_airflow/lib/python3.10/site-packages/kafka/consumer/group.py", line 356, in __init__
    self._client = KafkaClient(metrics=self._metrics, **self.config)
  File "/home/nizam/env_airflow/lib/python3.10/site-packages/kafka/client_async.py", line 244, in __init__
    self.config['api_version'] = self.check_version(timeout=check_timeout)
  File "/home/nizam/env_airflow/lib/python3.10/site-packages/kafka/client_async.py", line 900, in check_version
    raise Errors.NoBrokersAvailable()
kafka.errors.NoBrokersAvailable: NoBrokersAvailable
[2023-05-13T10:44:17.440+0530] {taskinstance.py:1368} INFO - Marking task as UP_FOR_RETRY. dag_id=test2, task_id=consume_from_kafka_task, execution_date=20230512T080619, start_date=20230513T051417, end_date=20230513T051417
[2023-05-13T10:44:17.452+0530] {standard_task_runner.py:104} ERROR - Failed to execute job 173 for task consume_from_kafka_task (NoBrokersAvailable; 10413)
[2023-05-13T10:44:17.474+0530] {local_task_job_runner.py:232} INFO - Task exited with return code 1
[2023-05-13T10:44:17.501+0530] {taskinstance.py:2674} INFO - 0 downstream tasks scheduled from follow-on schedule check
