[2023-05-17T13:22:21.562+0530] {taskinstance.py:1115} INFO - Dependencies not met for <TaskInstance: mongodb_to_kafka_and_consumer.read_and_send_task manual__2023-05-17T07:35:41.062330+00:00 [up_for_retry]>, dependency 'Not In Retry Period' FAILED: Task is not ready for retry yet but will be retried automatically. Current date is 2023-05-17T07:52:21.562508+00:00 and task will be retried at 2023-05-17T07:57:16.137274+00:00.
[2023-05-17T13:22:21.569+0530] {local_task_job_runner.py:161} INFO - Task is not able to be run
[2023-05-17T15:24:23.185+0530] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: mongodb_to_kafka_and_consumer.read_and_send_task manual__2023-05-17T07:35:41.062330+00:00 [queued]>
[2023-05-17T15:24:23.195+0530] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: mongodb_to_kafka_and_consumer.read_and_send_task manual__2023-05-17T07:35:41.062330+00:00 [queued]>
[2023-05-17T15:24:23.195+0530] {taskinstance.py:1331} INFO - Starting attempt 2 of 2
[2023-05-17T15:24:23.211+0530] {taskinstance.py:1350} INFO - Executing <Task(PythonOperator): read_and_send_task> on 2023-05-17 07:35:41.062330+00:00
[2023-05-17T15:24:23.216+0530] {standard_task_runner.py:57} INFO - Started process 11568 to run task
[2023-05-17T15:24:23.221+0530] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'mongodb_to_kafka_and_consumer', 'read_and_send_task', 'manual__2023-05-17T07:35:41.062330+00:00', '--job-id', '338', '--raw', '--subdir', 'DAGS_FOLDER/test1.py', '--cfg-path', '/tmp/tmp9z29a9pe']
[2023-05-17T15:24:23.222+0530] {standard_task_runner.py:85} INFO - Job 338: Subtask read_and_send_task
[2023-05-17T15:24:23.277+0530] {task_command.py:410} INFO - Running <TaskInstance: mongodb_to_kafka_and_consumer.read_and_send_task manual__2023-05-17T07:35:41.062330+00:00 [running]> on host nizam-HP-15-Notebook-PC
[2023-05-17T15:24:23.377+0530] {taskinstance.py:1568} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='mongodb_to_kafka_and_consumer' AIRFLOW_CTX_TASK_ID='read_and_send_task' AIRFLOW_CTX_EXECUTION_DATE='2023-05-17T07:35:41.062330+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-05-17T07:35:41.062330+00:00'
[2023-05-17T15:24:23.596+0530] {conn.py:380} INFO - <BrokerConnection node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: connecting to localhost:9092 [('127.0.0.1', 9092) IPv4]
[2023-05-17T15:24:23.597+0530] {conn.py:1205} INFO - Probing node bootstrap-0 broker version
[2023-05-17T15:24:23.597+0530] {conn.py:410} INFO - <BrokerConnection node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: Connection complete.
[2023-05-17T15:24:23.795+0530] {conn.py:1267} INFO - Broker version identified as 2.5.0
[2023-05-17T15:24:23.795+0530] {conn.py:1268} INFO - Set configuration api_version=(2, 5, 0) to skip auto check_version requests on startup
[2023-05-17T15:26:15.879+0530] {process_utils.py:131} INFO - Sending Signals.SIGTERM to group 11568. PIDs of all processes in the group: [11568]
[2023-05-17T15:26:15.881+0530] {process_utils.py:86} INFO - Sending the signal Signals.SIGTERM to group 11568
[2023-05-17T15:26:15.881+0530] {taskinstance.py:1540} ERROR - Received SIGTERM. Terminating subprocesses.
[2023-05-17T15:26:15.892+0530] {taskinstance.py:1847} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/nizam/env_airflow/lib/python3.10/site-packages/airflow/operators/python.py", line 181, in execute
    return_value = self.execute_callable()
  File "/home/nizam/env_airflow/lib/python3.10/site-packages/airflow/operators/python.py", line 198, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/home/nizam/airflow/dags/test1.py", line 39, in read_from_mongodb_and_send_to_kafka
    for document in cursor:
  File "/home/nizam/env_airflow/lib/python3.10/site-packages/pymongo/cursor.py", line 1248, in next
    if len(self.__data) or self._refresh():
  File "/home/nizam/env_airflow/lib/python3.10/site-packages/pymongo/cursor.py", line 1165, in _refresh
    self.__send_message(q)
  File "/home/nizam/env_airflow/lib/python3.10/site-packages/pymongo/cursor.py", line 1052, in __send_message
    response = client._run_operation(
  File "/home/nizam/env_airflow/lib/python3.10/site-packages/pymongo/_csot.py", line 105, in csot_wrapper
    return func(self, *args, **kwargs)
  File "/home/nizam/env_airflow/lib/python3.10/site-packages/pymongo/mongo_client.py", line 1330, in _run_operation
    return self._retryable_read(
  File "/home/nizam/env_airflow/lib/python3.10/site-packages/pymongo/_csot.py", line 105, in csot_wrapper
    return func(self, *args, **kwargs)
  File "/home/nizam/env_airflow/lib/python3.10/site-packages/pymongo/mongo_client.py", line 1448, in _retryable_read
    return func(session, server, sock_info, read_pref)
  File "/home/nizam/env_airflow/lib/python3.10/site-packages/pymongo/mongo_client.py", line 1326, in _cmd
    return server.run_operation(
  File "/home/nizam/env_airflow/lib/python3.10/site-packages/pymongo/server.py", line 115, in run_operation
    reply = sock_info.receive_message(request_id)
  File "/home/nizam/env_airflow/lib/python3.10/site-packages/pymongo/pool.py", line 821, in receive_message
    self._raise_connection_failure(error)
  File "/home/nizam/env_airflow/lib/python3.10/site-packages/pymongo/pool.py", line 819, in receive_message
    return receive_message(self, request_id, self.max_message_size)
  File "/home/nizam/env_airflow/lib/python3.10/site-packages/pymongo/network.py", line 217, in receive_message
    _receive_data_on_socket(sock_info, 16, deadline)
  File "/home/nizam/env_airflow/lib/python3.10/site-packages/pymongo/network.py", line 299, in _receive_data_on_socket
    chunk_length = sock_info.sock.recv_into(mv[bytes_read:])
  File "/usr/lib/python3.10/ssl.py", line 1274, in recv_into
    return self.read(nbytes, buffer)
  File "/usr/lib/python3.10/ssl.py", line 1130, in read
    return self._sslobj.read(len, buffer)
  File "/home/nizam/env_airflow/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 1542, in signal_handler
    raise AirflowException("Task received SIGTERM signal")
airflow.exceptions.AirflowException: Task received SIGTERM signal
[2023-05-17T15:26:15.902+0530] {taskinstance.py:1368} INFO - Marking task as FAILED. dag_id=mongodb_to_kafka_and_consumer, task_id=read_and_send_task, execution_date=20230517T073541, start_date=20230517T095423, end_date=20230517T095615
[2023-05-17T15:26:15.925+0530] {standard_task_runner.py:104} ERROR - Failed to execute job 338 for task read_and_send_task (Task received SIGTERM signal; 11568)
[2023-05-17T15:26:15.975+0530] {process_utils.py:79} INFO - Process psutil.Process(pid=11568, status='terminated', exitcode=1, started='15:24:22') (11568) terminated with exit code 1
