[2023-06-09T00:38:28.786+0530] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: storm_topoo.success_email_task manual__2023-06-08T19:07:30.112459+00:00 [queued]>
[2023-06-09T00:38:28.811+0530] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: storm_topoo.success_email_task manual__2023-06-08T19:07:30.112459+00:00 [queued]>
[2023-06-09T00:38:28.812+0530] {taskinstance.py:1331} INFO - Starting attempt 1 of 1
[2023-06-09T00:38:28.856+0530] {taskinstance.py:1350} INFO - Executing <Task(EmailOperator): success_email_task> on 2023-06-08 19:07:30.112459+00:00
[2023-06-09T00:38:28.863+0530] {standard_task_runner.py:57} INFO - Started process 19642 to run task
[2023-06-09T00:38:28.871+0530] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'storm_topoo', 'success_email_task', 'manual__2023-06-08T19:07:30.112459+00:00', '--job-id', '849', '--raw', '--subdir', 'DAGS_FOLDER/dag.py', '--cfg-path', '/tmp/tmpz5z8o8sf']
[2023-06-09T00:38:28.874+0530] {standard_task_runner.py:85} INFO - Job 849: Subtask success_email_task
[2023-06-09T00:38:29.050+0530] {task_command.py:410} INFO - Running <TaskInstance: storm_topoo.success_email_task manual__2023-06-08T19:07:30.112459+00:00 [running]> on host nizam-HP-15-Notebook-PC
[2023-06-09T00:38:29.294+0530] {taskinstance.py:1568} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='storm_topoo' AIRFLOW_CTX_TASK_ID='success_email_task' AIRFLOW_CTX_EXECUTION_DATE='2023-06-08T19:07:30.112459+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-06-08T19:07:30.112459+00:00'
[2023-06-09T00:38:29.322+0530] {logging_mixin.py:149} WARNING - /home/nizam/env_airflow/lib/python3.10/site-packages/airflow/utils/email.py:152 RemovedInAirflow3Warning: Fetching SMTP credentials from configuration variables will be deprecated in a future release. Please set credentials using a connection instead.
[2023-06-09T00:38:29.322+0530] {configuration.py:675} WARNING - section/key [smtp/smtp_user] not found in config
[2023-06-09T00:38:29.322+0530] {email.py:268} INFO - Email alerting: attempt 1
[2023-06-09T00:38:29.323+0530] {taskinstance.py:1847} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/nizam/env_airflow/lib/python3.10/site-packages/airflow/operators/email.py", line 77, in execute
    send_email(
  File "/home/nizam/env_airflow/lib/python3.10/site-packages/airflow/utils/email.py", line 78, in send_email
    return backend(
  File "/home/nizam/env_airflow/lib/python3.10/site-packages/airflow/utils/email.py", line 152, in send_email_smtp
    send_mime_email(e_from=mail_from, e_to=recipients, mime_msg=msg, conn_id=conn_id, dryrun=dryrun)
  File "/home/nizam/env_airflow/lib/python3.10/site-packages/airflow/utils/email.py", line 270, in send_mime_email
    smtp_conn = _get_smtp_connection(smtp_host, smtp_port, smtp_timeout, smtp_ssl)
  File "/home/nizam/env_airflow/lib/python3.10/site-packages/airflow/utils/email.py", line 317, in _get_smtp_connection
    else smtplib.SMTP(host=host, port=port, timeout=timeout)
  File "/usr/lib/python3.10/smtplib.py", line 255, in __init__
    (code, msg) = self.connect(host, port)
  File "/usr/lib/python3.10/smtplib.py", line 341, in connect
    self.sock = self._get_socket(host, port, self.timeout)
  File "/usr/lib/python3.10/smtplib.py", line 312, in _get_socket
    return socket.create_connection((host, port), timeout,
  File "/usr/lib/python3.10/socket.py", line 845, in create_connection
    raise err
  File "/usr/lib/python3.10/socket.py", line 833, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused
[2023-06-09T00:38:29.341+0530] {taskinstance.py:1368} INFO - Marking task as FAILED. dag_id=storm_topoo, task_id=success_email_task, execution_date=20230608T190730, start_date=20230608T190828, end_date=20230608T190829
[2023-06-09T00:38:29.374+0530] {standard_task_runner.py:104} ERROR - Failed to execute job 849 for task success_email_task ([Errno 111] Connection refused; 19642)
[2023-06-09T00:38:29.396+0530] {local_task_job_runner.py:232} INFO - Task exited with return code 1
[2023-06-09T00:38:29.426+0530] {taskinstance.py:2674} INFO - 0 downstream tasks scheduled from follow-on schedule check
