[2023-05-19T14:40:39.971+0530] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: mongodb_to_kafka_and_consumer.read_and_send_task manual__2023-05-19T06:48:50.704970+00:00 [queued]>
[2023-05-19T14:40:39.980+0530] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: mongodb_to_kafka_and_consumer.read_and_send_task manual__2023-05-19T06:48:50.704970+00:00 [queued]>
[2023-05-19T14:40:39.980+0530] {taskinstance.py:1331} INFO - Starting attempt 2 of 2
[2023-05-19T14:40:40.000+0530] {taskinstance.py:1350} INFO - Executing <Task(PythonOperator): read_and_send_task> on 2023-05-19 06:48:50.704970+00:00
[2023-05-19T14:40:40.005+0530] {standard_task_runner.py:57} INFO - Started process 22161 to run task
[2023-05-19T14:40:40.009+0530] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'mongodb_to_kafka_and_consumer', 'read_and_send_task', 'manual__2023-05-19T06:48:50.704970+00:00', '--job-id', '746', '--raw', '--subdir', 'DAGS_FOLDER/test1.py', '--cfg-path', '/tmp/tmp307mq4on']
[2023-05-19T14:40:40.010+0530] {standard_task_runner.py:85} INFO - Job 746: Subtask read_and_send_task
[2023-05-19T14:40:40.057+0530] {task_command.py:410} INFO - Running <TaskInstance: mongodb_to_kafka_and_consumer.read_and_send_task manual__2023-05-19T06:48:50.704970+00:00 [running]> on host nizam-HP-15-Notebook-PC
[2023-05-19T14:40:40.129+0530] {taskinstance.py:1568} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='mongodb_to_kafka_and_consumer' AIRFLOW_CTX_TASK_ID='read_and_send_task' AIRFLOW_CTX_EXECUTION_DATE='2023-05-19T06:48:50.704970+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-05-19T06:48:50.704970+00:00'
[2023-05-19T14:40:40.536+0530] {conn.py:380} INFO - <BrokerConnection node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: connecting to localhost:9092 [('127.0.0.1', 9092) IPv4]
[2023-05-19T14:40:40.536+0530] {conn.py:1205} INFO - Probing node bootstrap-0 broker version
[2023-05-19T14:40:40.537+0530] {conn.py:410} INFO - <BrokerConnection node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: Connection complete.
[2023-05-19T14:40:40.649+0530] {conn.py:1267} INFO - Broker version identified as 2.5.0
[2023-05-19T14:40:40.650+0530] {conn.py:1268} INFO - Set configuration api_version=(2, 5, 0) to skip auto check_version requests on startup
[2023-05-19T14:42:00.693+0530] {process_utils.py:131} INFO - Sending Signals.SIGTERM to group 22161. PIDs of all processes in the group: [22161]
[2023-05-19T14:42:00.694+0530] {process_utils.py:86} INFO - Sending the signal Signals.SIGTERM to group 22161
[2023-05-19T14:42:00.694+0530] {taskinstance.py:1540} ERROR - Received SIGTERM. Terminating subprocesses.
[2023-05-19T14:42:00.704+0530] {taskinstance.py:1847} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/nizam/env_airflow/lib/python3.10/site-packages/airflow/operators/python.py", line 181, in execute
    return_value = self.execute_callable()
  File "/home/nizam/env_airflow/lib/python3.10/site-packages/airflow/operators/python.py", line 198, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/home/nizam/airflow/dags/test1.py", line 57, in read_from_mongodb_and_send_to_kafka
    time.sleep(1)
  File "/home/nizam/env_airflow/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 1542, in signal_handler
    raise AirflowException("Task received SIGTERM signal")
airflow.exceptions.AirflowException: Task received SIGTERM signal
[2023-05-19T14:42:00.708+0530] {taskinstance.py:1368} INFO - Marking task as FAILED. dag_id=mongodb_to_kafka_and_consumer, task_id=read_and_send_task, execution_date=20230519T064850, start_date=20230519T091039, end_date=20230519T091200
[2023-05-19T14:42:00.735+0530] {standard_task_runner.py:104} ERROR - Failed to execute job 746 for task read_and_send_task (Task received SIGTERM signal; 22161)
[2023-05-19T14:42:00.747+0530] {process_utils.py:79} INFO - Process psutil.Process(pid=22161, status='terminated', exitcode=1, started='14:40:39') (22161) terminated with exit code 1
