[2023-06-12T14:48:48.913+0530] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: storm_top.send_email_task manual__2023-06-12T09:17:59.257419+00:00 [queued]>
[2023-06-12T14:48:48.930+0530] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: storm_top.send_email_task manual__2023-06-12T09:17:59.257419+00:00 [queued]>
[2023-06-12T14:48:48.930+0530] {taskinstance.py:1331} INFO - Starting attempt 1 of 1
[2023-06-12T14:48:48.960+0530] {taskinstance.py:1350} INFO - Executing <Task(PythonOperator): send_email_task> on 2023-06-12 09:17:59.257419+00:00
[2023-06-12T14:48:48.967+0530] {standard_task_runner.py:57} INFO - Started process 7959 to run task
[2023-06-12T14:48:48.974+0530] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'storm_top', 'send_email_task', 'manual__2023-06-12T09:17:59.257419+00:00', '--job-id', '949', '--raw', '--subdir', 'DAGS_FOLDER/dag.py', '--cfg-path', '/tmp/tmp90x8ln1j']
[2023-06-12T14:48:48.977+0530] {standard_task_runner.py:85} INFO - Job 949: Subtask send_email_task
[2023-06-12T14:48:49.048+0530] {task_command.py:410} INFO - Running <TaskInstance: storm_top.send_email_task manual__2023-06-12T09:17:59.257419+00:00 [running]> on host nizam-HP-15-Notebook-PC
[2023-06-12T14:48:49.581+0530] {taskinstance.py:1568} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='storm_top' AIRFLOW_CTX_TASK_ID='send_email_task' AIRFLOW_CTX_EXECUTION_DATE='2023-06-12T09:17:59.257419+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-06-12T09:17:59.257419+00:00'
[2023-06-12T14:48:49.599+0530] {base.py:73} INFO - Using connection ID 'smtp_default' for task execution.
[2023-06-12T14:48:49.600+0530] {email.py:268} INFO - Email alerting: attempt 1
[2023-06-12T14:48:49.602+0530] {logging_mixin.py:149} INFO - An error occurred while sending email: [Errno -3] Temporary failure in name resolution
[2023-06-12T14:48:49.602+0530] {taskinstance.py:1847} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/nizam/env_airflow/lib/python3.10/site-packages/airflow/operators/python.py", line 181, in execute
    return_value = self.execute_callable()
  File "/home/nizam/env_airflow/lib/python3.10/site-packages/airflow/operators/python.py", line 198, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/home/nizam/airflow/dags/dag.py", line 181, in send_email
    email_operator.execute(context=None)
  File "/home/nizam/env_airflow/lib/python3.10/site-packages/airflow/operators/email.py", line 77, in execute
    send_email(
  File "/home/nizam/env_airflow/lib/python3.10/site-packages/airflow/utils/email.py", line 78, in send_email
    return backend(
  File "/home/nizam/env_airflow/lib/python3.10/site-packages/airflow/utils/email.py", line 152, in send_email_smtp
    send_mime_email(e_from=mail_from, e_to=recipients, mime_msg=msg, conn_id=conn_id, dryrun=dryrun)
  File "/home/nizam/env_airflow/lib/python3.10/site-packages/airflow/utils/email.py", line 270, in send_mime_email
    smtp_conn = _get_smtp_connection(smtp_host, smtp_port, smtp_timeout, smtp_ssl)
  File "/home/nizam/env_airflow/lib/python3.10/site-packages/airflow/utils/email.py", line 317, in _get_smtp_connection
    else smtplib.SMTP(host=host, port=port, timeout=timeout)
  File "/usr/lib/python3.10/smtplib.py", line 255, in __init__
    (code, msg) = self.connect(host, port)
  File "/usr/lib/python3.10/smtplib.py", line 341, in connect
    self.sock = self._get_socket(host, port, self.timeout)
  File "/usr/lib/python3.10/smtplib.py", line 312, in _get_socket
    return socket.create_connection((host, port), timeout,
  File "/usr/lib/python3.10/socket.py", line 824, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
  File "/usr/lib/python3.10/socket.py", line 955, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -3] Temporary failure in name resolution
[2023-06-12T14:48:49.616+0530] {taskinstance.py:1368} INFO - Marking task as FAILED. dag_id=storm_top, task_id=send_email_task, execution_date=20230612T091759, start_date=20230612T091848, end_date=20230612T091849
[2023-06-12T14:48:49.639+0530] {standard_task_runner.py:104} ERROR - Failed to execute job 949 for task send_email_task ([Errno -3] Temporary failure in name resolution; 7959)
[2023-06-12T14:48:49.672+0530] {local_task_job_runner.py:232} INFO - Task exited with return code 1
[2023-06-12T14:48:49.697+0530] {taskinstance.py:2674} INFO - 0 downstream tasks scheduled from follow-on schedule check
