[2023-05-16T16:46:12.462+0530] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: storm_topology.submit_topology manual__2023-05-16T11:15:22.238801+00:00 [queued]>
[2023-05-16T16:46:12.472+0530] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: storm_topology.submit_topology manual__2023-05-16T11:15:22.238801+00:00 [queued]>
[2023-05-16T16:46:12.473+0530] {taskinstance.py:1331} INFO - Starting attempt 1 of 1
[2023-05-16T16:46:12.493+0530] {taskinstance.py:1350} INFO - Executing <Task(BashOperator): submit_topology> on 2023-05-16 11:15:22.238801+00:00
[2023-05-16T16:46:12.497+0530] {standard_task_runner.py:57} INFO - Started process 48311 to run task
[2023-05-16T16:46:12.501+0530] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'storm_topology', 'submit_topology', 'manual__2023-05-16T11:15:22.238801+00:00', '--job-id', '282', '--raw', '--subdir', 'DAGS_FOLDER/kafkastorm.py', '--cfg-path', '/tmp/tmp4eiq4s98']
[2023-05-16T16:46:12.503+0530] {standard_task_runner.py:85} INFO - Job 282: Subtask submit_topology
[2023-05-16T16:46:12.558+0530] {task_command.py:410} INFO - Running <TaskInstance: storm_topology.submit_topology manual__2023-05-16T11:15:22.238801+00:00 [running]> on host nizam-HP-15-Notebook-PC
[2023-05-16T16:46:12.638+0530] {taskinstance.py:1568} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='your_name' AIRFLOW_CTX_DAG_ID='storm_topology' AIRFLOW_CTX_TASK_ID='submit_topology' AIRFLOW_CTX_EXECUTION_DATE='2023-05-16T11:15:22.238801+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-05-16T11:15:22.238801+00:00'
[2023-05-16T16:46:12.641+0530] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2023-05-16T16:46:12.642+0530] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'cd /home/nizam/project/project/storm/project/Kafka-Storm && sparse run --name first_topology']
[2023-05-16T16:46:12.651+0530] {subprocess.py:86} INFO - Output:
[2023-05-16T16:46:25.280+0530] {subprocess.py:93} INFO - Cleaning from prior builds...
[2023-05-16T16:46:27.938+0530] {subprocess.py:93} INFO - Creating topology Uber-JAR...
[2023-05-16T16:46:46.092+0530] {process_utils.py:131} INFO - Sending Signals.SIGTERM to group 48311. PIDs of all processes in the group: [48312, 48447, 48448, 48455, 48311]
[2023-05-16T16:46:46.093+0530] {process_utils.py:86} INFO - Sending the signal Signals.SIGTERM to group 48311
[2023-05-16T16:46:46.093+0530] {taskinstance.py:1540} ERROR - Received SIGTERM. Terminating subprocesses.
[2023-05-16T16:46:46.094+0530] {subprocess.py:104} INFO - Sending SIGTERM signal to process group
[2023-05-16T16:46:46.107+0530] {process_utils.py:79} INFO - Process psutil.Process(pid=48447, status='terminated', started='16:46:27') (48447) terminated with exit code None
[2023-05-16T16:46:46.115+0530] {taskinstance.py:1847} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/nizam/env_airflow/lib/python3.10/site-packages/airflow/operators/bash.py", line 201, in execute
    result = self.subprocess_hook.run_command(
  File "/home/nizam/env_airflow/lib/python3.10/site-packages/airflow/hooks/subprocess.py", line 91, in run_command
    for raw_line in iter(self.sub_process.stdout.readline, b""):
  File "/home/nizam/env_airflow/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 1542, in signal_handler
    raise AirflowException("Task received SIGTERM signal")
airflow.exceptions.AirflowException: Task received SIGTERM signal
[2023-05-16T16:46:46.128+0530] {taskinstance.py:1368} INFO - Marking task as FAILED. dag_id=storm_topology, task_id=submit_topology, execution_date=20230516T111522, start_date=20230516T111612, end_date=20230516T111646
[2023-05-16T16:46:46.152+0530] {standard_task_runner.py:104} ERROR - Failed to execute job 282 for task submit_topology (Task received SIGTERM signal; 48311)
[2023-05-16T16:46:46.201+0530] {process_utils.py:79} INFO - Process psutil.Process(pid=48455, status='terminated', started='16:46:27') (48455) terminated with exit code None
[2023-05-16T16:46:46.202+0530] {process_utils.py:79} INFO - Process psutil.Process(pid=48311, status='terminated', exitcode=1, started='16:46:11') (48311) terminated with exit code 1
[2023-05-16T16:46:46.203+0530] {process_utils.py:79} INFO - Process psutil.Process(pid=48448, status='terminated', started='16:46:27') (48448) terminated with exit code None
[2023-05-16T16:46:46.204+0530] {process_utils.py:79} INFO - Process psutil.Process(pid=48312, status='terminated', started='16:46:11') (48312) terminated with exit code None
